name: "Deployment"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4
      - run: terraform init
      - run: echo "$TFVARS" > dave.tfvars
        env:
          TFVARS: ${{ secrets.TFVARS }}
      - id: plan
        run: terraform apply -auto-approve -var-file dave.tfvars
